[package]
name = "cense"
version = "0.1.0"
description="Simple tool for license file fast creation"
authors = ["Wafelack <wafelack@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
